language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t cpinochet/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true cpinochet/docker-react npm run test