language: generic
sudo: required
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_4400f5eddadb_key -iv $encrypted_4400f5eddadb_iv
  -in llave.json.enc -out /tmp/llave.json -d
- docker build -t cpinochet/docker-react -f Dockerfile.dev .
script:
- docker run -e CI=true cpinochet/docker-react npm run test
deploy:
  provider: gae
  keyfile: /tmp/llave.json
  project: hopeful-vim-285617
